#!/bin/bash

# Specify the number of cores (n=10), nodes (N=1)
#SBATCH -o tensorflow_script.sh.log-%j-%a
#SBATCH -e tensorflow_error_%j-%a.txt
#SBATCH -t 0-20:00
#SBATCH -p sched_mit_andrewv
#SBATCH -n 10
#SBATCH -N 1
#SBATCH --mail-user=mcnaomi@mit.edu
#SBATCH --mail-type=ALL

# Loading the required modules
module load anaconda3/2021.11
source activate tensorflow_env_no_builds_non_OS

# Run the script
python3 SimpleParallelScript.py
